<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>VideoCaptureWPF</RootNamespace>
    <AssemblyName>VideoCaptureWPF</AssemblyName>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  
  <ItemGroup>
    <None Include="haarcascade_frontalface_default.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="OpenCvSharp5.runtime.win" Version="5.0.0.20260702-beta" />
    <PackageReference Include="OpenCvSharp5.WpfExtensions" Version="5.0.0.20260702-beta" />
  </ItemGroup>
  
</Project>