<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Data\Image\box_in_scene.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Data\Image\box_in_scene.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenCvSharp5.runtime.win" Version="5.0.0.20260702" />
    <PackageReference Include="OpenCvSharp5.WpfExtensions" Version="5.0.0.20260702" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Data\Image\fruits.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
