<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>VideoCaptureForm</RootNamespace>
    <AssemblyName>VideoCaptureForm</AssemblyName>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenCvSharp5.runtime.win" Version="5.0.0.20260723" />
    <PackageReference Include="OpenCvSharp5.GdipExtensions" Version="5.0.0.20260723" />
  </ItemGroup>

  <ItemGroup>
    <None Include="haarcascade_frontalface_default.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
